hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

algorithm:
  action_credit_ratio: 0.8

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang_async
    multi_turn:
      enable: True
      max_turns: 12
      format: qwen
      model_name: gpt-4o-mini
      # tool_config_path: "./config/tool_config/interact_tool_config.yaml"
